travis:
  secure:
    BINSTAR_TOKEN: I5mxTiAFDHHWUAXXctQTSKXfDadBUDQGjWRbxItY9aDmLYvPblwyLXjbyPqu+BCrPtqtQjq9fSAwG/KCI6gD5LVd+OhP/izLYJ3GvI9PNRHpcwjr+LKtWuEFoVQHRuP3FmawYtr2icXbAZdYWGatwIX8cChSfEjQ+9dOzcBF1KJXx+YB7KlQch5synwWr0ZLE4QtVCmSOO/wWYrCB16pJZMZ9Z8OPaa7PQOhaBqiN5mfKApkEa8PD0pfmbLwwCuYS5H7izlA8XS8VD5r/9qwH1Y4Y3W9NcsTzFvrDky08bfPVdTV5FcpRUNI4jbiBubnQUAhViKJjNFVxzNZl50VqeqqH00vbWV2m5SkZxE0CLedlugSnG8dAFDRaa4IRd5bjWC77DCcjji/EdfCt7rWkHw2qDjqDIIlyLUacmEejQqvGh9jo16XSAGG5Si67Cx9OrcTD0LwYJVt5E5u4KKv3E2DriPa3Cpjo56GLPmv5G8m+vYj97YLeeJ+r26Fotdk0iMPywvvVddHODRah0nGNuFV1oWClXEm9Ci0bPl92NA74cfgr0mYY2UMHEPmjwBrERYWlSGTX0yYeYcgpQ/dSsSi0IzaUiyZfY+tNv0wtP/57PPueAQ3Cc3unP0FAwVhq3l7c0mJ1RNVjx7sIFngUraHM6d0gCEhtsN4FY+KiAY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
