travis:
  secure:
    BINSTAR_TOKEN: sAm3lI5Js++SD50mDZdkOYdBTfEtwULpMnZKGw8JoZFKeY8gSQf2lk72hsKwwszcuhY3CkQn+lH4JSzbsoy5LxXxoH1IpXUKTooUixvcCtP7QbXqqAqh9khCeVph73dn4iwCKjDAFAuat8ATJAOLgHEkkMcdrxFFuWSD7FUxmDVMxLk/ws0Wqh14i+nyXAiExtWZUkcmuwUNq4HofILL4+tOX32l1nnRzBGfiQtK4EBukq8RTTF5xVpoUcRR7fWfCoV0ycQZspsWuXAD5NQMzdQH1r+xERepdvp+iUJwwm6Y2amO2c640ZJorg+R4nRXL08r5cyQ66Ao8ajfYOaLD+WM7EMZbb8a/54yHsttsHNvACORPhqPhIwx+uUho4tRPrBD/dE3iyzBWJda6y2e+XcinOwMR7eQREqby0P4mZpbqfI4w+E/N5svpSq+Ga8nUw3/JPWEaVq3rgmBrVwWpFMOkT8DAeUjM3peyRKYsRzlTO9iWEGpqrKCq3+vML/H5O7vBsh1gZB1Gchpl05xTIeyjDYtlh7kaw7zeoLKJ6QWiFQG1Lb9rtQzDYlIj+Io+orf3sfXGLwst2c7QqicxfgIXnDAu44jtuNp5MrZydB393m09/WRDOf8uYyT0OmAe24zy8YXG874NmQzlII8GhtVmTmjPJBlhbnHsUP+lvI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
